### ISSUE TITLE
Summer 2022 season won't load.

### ISSUE THREAD

**Issue by Artins90** [QikLiang/AptxShows#1]
Not sure if this is the correct place to report it but currently the Summer 2022 season is not loading on http://aptxshows.moe/
All the other functions seem to work correctly.

**Comment by QikLiang** [comment]
I'm impressed you found this repo that's not been advertised anywhere, but yes I welcome the feedback (and any other while you're at it). I forgot to restart the cache update process when the server has to be restarted, which has been resolved.

**Comment by Artins90** [comment]
I found this repo via google search, the website is mentioned in the About section and I guess Google keeps track of all the github repos.
I think this tool should have more recognition, it allowed me to find many shows I enjoyed that I would have otherwise not even considered.
Thank you for fixing it.
