### ISSUE TITLE
The spring 2024 data appears to be missing

### ISSUE THREAD

**Issue by Artins90** [QikLiang/AptxShows#2]
Selecting spring 2024 returns the message: Something went wrong.
Winter 2023 works without problems using the same Anilist account.

EDIT: it looks like my brain failed me, recently I keep hearing 新春 (shin shun, literally "new spring" but actually it indicates the period at the beginning of the new year) and I associated it with spring (shun 春) and the spring anime season.
This led me to look for the spring season thinking it was the current one.

**Comment by QikLiang** [comment]
The spring 2024 section was visible but hangs because the database updating process crashed two weeks ago. Now that I've restarted it, the results for winter 2024 should be slightly updated, and spring 2024 is now visible.
